### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by HotelNimara** [MinecraftXPert/Economy-Bot#1]
Are you still working on this project? @MinecraftXPert

**Comment by MinecraftXPert** [comment]
Not really lol

**Comment by HotelNimara** [comment]
> Not really lol

Oh, I thought you were going to continue this project, I think I'll be a part of future features. @MinecraftXPert

**Comment by MinecraftXPert** [comment]
I've been working on and off with it. If you want you can contribute I just gotta make sure the code is fine
